Repository Badgerati/Pode.Web, pull requests merged in 2024-10, with the labels that each got.

#629 Fixes the scope for how styles and classes are added
  docs/Tutorials/ClassAndStyles.md
  examples/inputs.ps1
  examples/login-oauth2.ps1
  src/Pode.Web.psd1
  src/Public/Actions.ps1
  src/Templates/Public/scripts/templates.js
  src/Templates/Public/styles/default.css
  src/Templates/Views/index.pode
  src/Templates/Views/shared/head.pode
Labels: bug :bug:

#619 Enabling Docker tags for preview builds
  .build.ps1
Labels: packaging :package:

#607 Fix issue that the Step does not transition
  src/Templates/Public/scripts/templates.js
Labels: bug :bug:

#631 Removes the Interval restriction on Timers, so values of 1+ seconds can be supplied
  docs/Tutorials/Elements/Timer.md
  examples/full.ps1
  src/Public/Elements.ps1
  src/Templates/Public/scripts/templates.js
Labels: enhancement :arrow_up:

#632 New lines in Paragraph/Text Element values are now properly rendered
  examples/paragraphs.ps1
  src/Templates/Public/scripts/default.js
  src/Templates/Public/scripts/templates.js
Labels: enhancement :arrow_up:
