Repository Badgerati/Pode.Web, pull requests merged in 2024-05, with the labels that each got.

#561 Fix typo in CommentBlock.md
  docs/Tutorials/Elements/CommentBlock.md
Labels: documentation :book:

#550 Update Pages.ps1
  src/Public/Pages.ps1
Labels: bug :bug:

#569 Bump bootstrap to v4.6.2
  package.json
Labels: packaging :package:

#571 Add support for logically grouping element together
  docs/Tutorials/Actions/ElementGroup.md
  docs/Tutorials/Actions/Elements.md
  docs/Tutorials/Elements/Accordion.md
  docs/Tutorials/Elements/Breadcrumbs.md
  docs/Tutorials/Elements/Card.md
  docs/Tutorials/Elements/Carousel.md
  docs/Tutorials/Elements/Container.md
  docs/Tutorials/Elements/ElementGroup.md
  docs/Tutorials/Elements/Grid.md
  docs/Tutorials/Elements/Hero.md
  docs/Tutorials/Elements/Modal.md
  docs/Tutorials/Elements/Span.md
  docs/Tutorials/Elements/Steps.md
  docs/Tutorials/Elements/Tabs.md
  docs/images/element_group_custom_layout.png
  docs/images/element_group_grp_in_grp.png
  docs/images/element_group_simple.png
  docs/images/span_example.png
  examples/element-groups.ps1
  src/Public/Actions.ps1
  src/Public/Elements.ps1
  src/Templates/Public/scripts/templates.js
Labels: feature :sunny:

#572 Fix encoding for Name, Placeholder, and Title when they contain certain special chars
  src/Templates/Public/scripts/default.js
  src/Templates/Public/scripts/templates.js
Labels: bug :bug:

#573 Add mike to mkdocs to support multiple doc versions
  .build.ps1
  .gitignore
  docs/release-notes.md
  mkdocs-overrides/main.html
  mkdocs-overrides/outdated.html
  mkdocs.yml
  src/Pode.Web.psd1
Labels: documentation :book:
